### PR TITLE
Bump `balanced-match`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
Build failing due to [an issue](https://github.com/babel/babel-eslint/issues/243) with `babel-eslint` used.

**Comment by MoOx** [comment]
@wtgtybhertgeghgtwtg the issue has been fixed. Do you mind updating what's need to be?

**Comment by wtgtybhertgeghgtwtg** [comment]
I'll file another PR to bump `babel` and co.

**Comment by wtgtybhertgeghgtwtg** [comment]
This was also fixed in `master`.

**Pull request closed without merging**
