### PR TITLE
Update `babel`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
Updates `babel`, `babel-eslint`, and `babel-tape-runner`.

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
`.eslintignore` keeps popping out of existence on Travis.

**Comment by MoOx** [comment]
I saw we are using node 0.10, maybe we should update that. Not sure how this can be related tho :)

**Comment by wtgtybhertgeghgtwtg** [comment]
What version do you want to support?
Actually, if you bump the version, you could probably just drop `babel`.

**Comment by MoOx** [comment]
what about node4+?

**Comment by MoOx** [comment]
node 4,6,8

**Comment by wtgtybhertgeghgtwtg** [comment]
This is already fixed in master.

**Pull request closed without merging**
