### PR TITLE
Support PostCSS 8

### PR DESCRIPTION
**Pull request by Semigradsky**

### CODE REVIEW

**Comment by giotramu** [comment]
Any update on this PR?

**Comment by michgeek** [comment]
I think this PR should not include the `yarn.lock`

**Comment by Semigradsky** [comment]
Why not? We can lock `devDependencies`
https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by Airkro** [comment]
Some people think the lock file should be committed in a team project(or big project), shouldn't commit in a single library repos.

But whatever, don't let the lock file problem block this pr.

**Pull request merged**
